-- Which customers have the highest total purchase value and how does their purchase behavior change over time?
-- Can you identify any trends or patterns in their purchasing habits?
SELECT
	date_trunc('quarter', new_invoice_date) AS quarter_period,
	SUM(price) AS total_purchase
FROM
	v2retail_sales
WHERE customer_id IN (
	SELECT customer_id
	FROM v2retail_sales
	GROUP BY customer_id
	ORDER BY SUM(price) DESC
	LIMIT 5)
GROUP BY
	quarter_period
ORDER BY
	quarter_period;

-- How has the total revenue generated by each country changed over time?
-- Can you identify any countries that are growing or declining in terms of sales?
WITH country_sales AS (
SELECT
	country,
	date_trunc('quarter', new_invoice_date) AS time_period,
	SUM(price) AS total_country_per_quarter
FROM
	v2retail_sales
GROUP BY
	country, time_period
ORDER BY
	country, time_period
)
SELECT
	country,
	time_period,
	ROUND((total_country_per_quarter / LAG(total_country_per_quarter) OVER (PARTITION BY country ORDER BY time_period)) - 1, 2) AS pct_change
FROM
	country_sales
ORDER BY
	country,
	time_period;

-- How many new customers did the company acquire each month, and what was the total revenue generated by these new customers compared to returning customers?
-- Can you identify any trends or patterns in customer acquisition and retention?

WITH customer_first_purchase AS (
	SELECT
		customer_id,
		date_trunc('month', MIN (new_invoice_date)) AS first_purchase_month
	FROM
		v2retail_sales
	GROUP BY
		customer_id
),
customer_type AS (
	SELECT
		customer_id,
		CASE
			WHEN date_trunc('month', new_invoice_date) = first_purchase_month THEN 'new'
			ELSE 'returning'
		END AS type
	FROM
		v2retail_sales
	LEFT JOIN
		customer_first_purchase USING (customer_id)
)

SELECT
	date_trunc('month', new_invoice_date) AS month,
	type,
	SUM(price) AS total_revenue,
	COUNT(DISTINCT CASE WHEN type = 'new' THEN customer_id END) AS new_customers,
	COUNT(DISTINCT CASE WHEN type = 'returning' THEN customer_id END) AS returning_customers
FROM
	v2retail_sales
LEFT JOIN
	customer_type USING (customer_id)
GROUP BY
	month, type
ORDER BY
	month, type;
	
--
