-- Which customers have the highest total purchase value and how does their purchase behavior change over time?
-- Can you identify any trends or patterns in their purchasing habits?
SELECT
	date_trunc('quarter', new_invoice_date) AS quarter_period,
	SUM(price) AS total_purchase
FROM
	v2retail_sales
WHERE customer_id IN (
	SELECT customer_id
	FROM v2retail_sales
	GROUP BY customer_id
	ORDER BY SUM(price) DESC
	LIMIT 5)
GROUP BY
	quarter_period
ORDER BY
	quarter_period;

-- How has the total revenue generated by each country changed over time?
-- Can you identify any countries that are growing or declining in terms of sales?
WITH country_sales AS (
SELECT
	country,
	date_trunc('quarter', new_invoice_date) AS time_period,
	SUM(price) AS total_country_per_quarter
FROM
	v2retail_sales
GROUP BY
	country, time_period
ORDER BY
	country, time_period
)
SELECT
	country,
	time_period,
	ROUND((total_country_per_quarter / LAG(total_country_per_quarter) OVER (PARTITION BY country ORDER BY time_period)) - 1, 2) AS pct_change
FROM
	country_sales
ORDER BY
	country,
	time_period;

--
